version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: brand-intelligence-postgres
    environment:
      POSTGRES_USER: brand_user
      POSTGRES_PASSWORD: brand_pass_dev
      POSTGRES_DB: brand_intelligence
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brand_user -d brand_intelligence"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - brand_network

  redis:
    image: redis:7-alpine
    container_name: brand-intelligence-redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - brand_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  brand_network:
    driver: bridge
